name: Release

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  linux-builds:
    name: Linux Builds
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        goos: [linux]
        goarch:
          [
            386,
            amd64,
            arm64,
            mips,
            mips64,
            mips64le,
            mipsle,
            ppc64,
            ppc64le,
            riscv64,
            s390x,
          ]

    steps:
      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Get Version
        id: tag-name
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w -X github.com/sliverarmory/sliver-sdk/cmd.Version=${{ steps.tag-name.outputs.version }}" -o ./sliver-sdk_${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-builds
          path: ./sliver-sdk_*

  bsd-builds:
    name: BSD Builds
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        goos: [darwin, freebsd, openbsd, netbsd]
        goarch: [amd64, arm64]

    steps:
      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Get Version
        id: tag-name
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w -X github.com/sliverarmory/sliver-sdk/cmd.Version=${{ steps.tag-name.outputs.version }}" -o ./sliver-sdk_${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bsd-builds
          path: ./sliver-sdk_*

  windows-builds:
    name: Windows Builds
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        goos: [windows]
        goarch: [386, amd64, arm64]

    steps:
      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Get Version
        id: tag-name
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w -X github.com/sliverarmory/sliver-sdk/cmd.Version=${{ steps.tag-name.outputs.version }}" -o ./sliver-sdk_${{ matrix.goos }}-${{ matrix.goarch }}.exe .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-builds
          path: ./sliver-sdk_*

  tagged-release:
    needs: [linux-builds, bsd-builds, windows-builds]

    name: "Tagged Release"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Get Version
        id: tag-name
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - run: mkdir -p ./builds
      - uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: Move Builds
        run: |
          mkdir ./release
          mv ./builds/linux-builds/* ./release/
          mv ./builds/bsd-builds/* ./release/
          mv ./builds/windows-builds/* ./release/

      - name: "Publish Release"
        uses: "bishopfox/action-gh-release@v1"
        with:
          tag_name: ${{ steps.tag-name.outputs.version }}
          files: |
            ./release/*
